Sending magic packet to 255.255.255.255:9 with BC:5F:F4:5C:85:B9
Sending magic packet to 255.255.255.255:9 with BC:5F:F4:5C:85:B9
Sending magic packet to 255.255.255.255:9 with BC:5F:F4:5C:85:B9
Sending magic packet to 255.255.255.255:9 with BC:5F:F4:5C:85:B9
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 122, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 122, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Sending magic packet to 255.255.255.255:9 with BC:5F:F4:5C:85:B9
Sending magic packet to 255.255.255.255:9 with BC:5F:F4:5C:85:B9
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2.py", line 141, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
Traceback (most recent call last):
  File "dischat_2_w.py", line 10, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 34, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 341, in <module>
    from . import _lxml
  File "/usr/lib/python3/dist-packages/bs4/builder/_lxml.py", line 16, in <module>
    from lxml import etree
  File "src/lxml/etree.pyx", line 504, in init lxml.etree
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 148, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.7/sre_compile.py", line 120, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
  File "/usr/lib/python3.7/sre_compile.py", line 295, in _optimize_charset
    charmap[av] = 1
KeyboardInterrupt
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "dischat_2_w.py", line 176, in on_message
    await message.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Error! 지역 검색 오류!
Error! 지역 검색 오류!
Error! 지역 검색 오류!
Error! 지역 검색 오류!
Error! 지역 검색 오류!
